CREATE DATABASE EmployeeDb;
GO
USE EmployeeDb;
GO

CREATE TABLE Employees (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Position NVARCHAR(100) NULL,
    Department NVARCHAR(100) NULL,
    Salary DECIMAL(18,2) NOT NULL
);
GO
